import { User, Guide, Booking, BookingStatus } from '../types';

export const mockUser: User = {
  id: 'user-1',
  name: 'Priya Sharma',
  email: 'priya.sharma@example.com',
  avatarUrl: 'https://picsum.photos/seed/priya/200/200',
  preferences: ['Historical Sites', 'Local Cuisine', 'Nature Walks'],
  emergencyContact: {
    name: 'Anil Sharma',
    phone: '+91 98765 43210',
  },
  isPro: false,
  points: 3940, // Sum of points from completed bookings
};

export const mockGuides: Guide[] = [
  {
    id: 'guide-1',
    name: 'Rohan Patil',
    location: 'Mumbai',
    avatarUrl: 'https://picsum.photos/seed/rohan/300/300',
    rating: 4.9,
    reviewCount: 124,
    languages: ['English', 'Hindi', 'Marathi'],
    specialties: ['Street Food', 'Bollywood Tours', 'History'],
    bio: 'Born and raised in Mumbai, I know every nook and cranny of this vibrant city. Let me show you the real Mumbai, from hidden food gems to the glamour of Bollywood.',
    pricePerDay: 4500,
    isVerified: true,
    gallery: ['https://picsum.photos/seed/mumbai1/600/400', 'https://picsum.photos/seed/mumbai2/600/400', 'https://picsum.photos/seed/mumbai3/600/400'],
  },
  {
    id: 'guide-2',
    name: 'Aisha Khan',
    location: 'Pune',
    avatarUrl: 'https://picsum.photos/seed/aisha/300/300',
    rating: 4.8,
    reviewCount: 98,
    languages: ['English', 'Hindi'],
    specialties: ['Trekking', 'Forts', 'Cultural Heritage'],
    bio: 'An avid trekker and history enthusiast, I specialize in tours around Pune, exploring the majestic forts of the Sahyadri mountains and the rich Maratha history.',
    pricePerDay: 4000,
    isVerified: true,
    gallery: ['https://picsum.photos/seed/pune1/600/400', 'https://picsum.photos/seed/pune2/600/400', 'https://picsum.photos/seed/pune3/600/400'],
  },
  {
    id: 'guide-3',
    name: 'Vikram Singh',
    location: 'Aurangabad',
    avatarUrl: 'https://picsum.photos/seed/vikram/300/300',
    rating: 4.9,
    reviewCount: 150,
    languages: ['English', 'Hindi', 'Marathi'],
    specialties: ['Ajanta & Ellora Caves', 'Mughal History', 'Archaeology'],
    bio: 'Explore the timeless wonders of Ajanta and Ellora with a certified archaeologist. I provide in-depth tours that bring ancient history to life.',
    pricePerDay: 5500,
    isVerified: true,
    gallery: ['https://picsum.photos/seed/caves1/600/400', 'https://picsum.photos/seed/caves2/600/400', 'https://picsum.photos/seed/caves3/600/400'],
  },
  {
    id: 'guide-4',
    name: 'Sunita Gawde',
    location: 'Nashik',
    avatarUrl: 'https://picsum.photos/seed/sunita/300/300',
    rating: 4.7,
    reviewCount: 75,
    languages: ['English', 'Marathi'],
    specialties: ['Vineyard Tours', 'Spiritual Sites', 'Local Cuisine'],
    bio: 'Discover Nashik, the wine capital of India! I offer exclusive tours of the best vineyards, combined with visits to sacred temples and delicious local food experiences.',
    pricePerDay: 3800,
    isVerified: false,
    gallery: ['https://picsum.photos/seed/nashik1/600/400', 'https://picsum.photos/seed/nashik2/600/400', 'https://picsum.photos/seed/nashik3/600/400'],
  },
];

export const mockBookings: Booking[] = [
    {
        id: 'booking-1',
        userId: 'user-1',
        guideId: 'guide-2',
        startDate: '2024-08-15',
        endDate: '2024-08-17',
        guests: 2,
        totalPrice: 24000,
        status: BookingStatus.Upcoming,
        pointsEarned: 2400,
    },
    {
        id: 'booking-2',
        userId: 'user-1',
        guideId: 'guide-1',
        startDate: '2024-05-20',
        endDate: '2024-05-21',
        guests: 1,
        totalPrice: 9000,
        status: BookingStatus.Completed,
        pointsEarned: 900,
    },
     {
        id: 'booking-3',
        userId: 'user-1',
        guideId: 'guide-4',
        startDate: '2024-03-10',
        endDate: '2024-03-12',
        guests: 4,
        totalPrice: 30400,
        status: BookingStatus.Completed,
        pointsEarned: 3040,
    },
];
